server:
  port: 8765
spring:
  application:
    name: api-gateway
    
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#  cloud:
#    gateway:
#      routes:
#      - id: userms
#        uri: lb://user-ms
#        predicates:
#        - Path=/user-ms/**
#        filters:
#        - RewritePath=/user-ms/(?<path>.*),/$\{path}
          
          